services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ecom-micro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommicro
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  user-service:
    build: ./user
    container_name: user-service
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommicro
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8085:8080"

  product-service:
    build: ./product
    container_name: product-service
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommicro
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8086:8080"

volumes:
  mysql_data:
